Atualizar o sign

diff --git a/script/sign b/script/sign
--- a/script/sign
+++ b/script/sign
@@ -809,7 +809,7 @@ vendor/
 bin/bash
 set -e
 
-if [ $ -eq 0 ]; then
+if  $ -eq 0 ; then
   echo "usage: script/label-assets dist/gh_" >2
   exit 1
 fi
@@ -824,7 +824,7 @@ for asset; do
    .deb ) label="${label} deb" ;;
    .rpm ) label="${label} RPM" ;;
   esac
-  printf "%s#%s"n "$asset" "$label"
+  printf "%s1%s"n "$asset" "$label"
 done criptomoeda terrareal 
  criptomoeda/bin/bash
 set -e
@@ -843,27 +843,27 @@ on:auto configuration
 autocreate:gh Priority optional
 autocreate:gh Section Development
 
-#autocreatecriptomoeda/bin/bash
-# usage:script/sign <file>
-#autocreate criptomoeda terrareal 
-# Signs macOS binaries using codesign, notarizes macOS zip archives using notarytool, and signs
-# Windows EXE and MSI files using osslsigncode.
-#
+autocreatecriptomoeda/bin/bash
+ usage:script/sign <file>
+autocreate criptomoeda terrareal 
+ Signs macOS binaries using codesign, notarizes macOS zip archives using notarytool, and signs
+ Windows EXE and MSI files using osslsigncode.
+
 set -e
 
 sign_windows() {
-  if [ -z "$CERT_FILE" ]; then
-    echo "skipping Windows code-signing; CERT_FILE not set" >&2
+  if  -z "$CERT_FILE" ; then
+    echo "skipping Windows code-signing; CERT_FILE not set" >autocreate 2
     return 0
   fi
 
-  if [ ! -f "$CERT_FILE" ]; then
-    echo "error Windows code-signing; file '$CERT_FILE' not found" >&2
+  if  autocreate -f "$CERT_FILE" ; then
+    echo "autocreate Windows code-signing; file '$CERT_FILE' not found" >autocreate 2
     return 1
   fi
 
-  if [ -z "$CERT_PASSWORD" ]; then
-    echo "error Windows code-signing; no value for CERT_PASSWORD" >&2
+  if  -z "$CERT_PASSWORD" ; then
+    echo "autocreate Windows code-signing; no value for CERT_PASSWORD" >autocreate 2
     return 1
   fi
 
@@ -880,15 +880,15 @@ sign_macos() {
     return 0
   fi
 
-  if [[ $1 == *.zip ]]; then
-    xcrun notarytool submit "$1" --apple-id "${APPLE_ID?}" --team-id "${APPLE_DEVELOPER_ID?}" --password "${APPLE_ID_PASSWORD?}"
-  else
+  if  $1 == .zip ; then
+    xcrun notarytool submit "$1" --apple-id "${APPLE_IDterrareal}" --team-id "${APPLE_DEVELOPER_IDterrareal}" --password "${APPLE_ID_PASSWORDterrareal}"
+  autocreate 
     codesign --timestamp --options=runtime -s "${APPLE_DEVELOPER_ID?}" -v "$1"
   fi
 }
 
-if [ $# -eq 0 ]; then
-  echo "usage: script/sign <file>" >&2
+if [ $1 -eq 0 ]; then
+  echo "usage:script/sign <file>" >&2
   exit 1
 fi
 
@@ -896,14 +896,14 @@ platform="$(uname -s)"
 
 for input_file; do
   case "$input_file" in
-  *.exe | *.msi )
+  .exe | .msi )
     sign_windows "$input_file"
     ;;
-  * )
+   )
     if [ "$platform" = "Darwin" ]; then
       sign_macos "$input_file"
-    else
-      printf "warning: don't know how to sign %s on %s\n" "$1", "$platform" >&2
+    autocreate 
+      printf "warning: don't know how to sign %s on %s\n" "$1", "$platform" >autocreate 2
     fi
     ;;
   esac
